name: CI

on:
  push:
    branches:
      - utkarsh/github-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $GITHUB_ENV

      # Step 3: Load Rust environment
      - name: Load Rust environment
        run: |
          source $GITHUB_ENV
          rustc --version # Verify Rust installation

      # Step 4: Install Solana CLI
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> $GITHUB_ENV

      # Step 5: Load Solana environment
      - name: Load Solana environment
        run: |
          source $GITHUB_ENV
          echo "Current PATH: $PATH"
          solana --version # Verify Solana installation

      # Step 6: Install AVM
      - name: Install AVM
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli
          echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $GITHUB_ENV

      # Step 7: Configure Solana and Build
      - name: Configure Solana and Build
        run: |
          source $GITHUB_ENV
          solana config set --url https://api.devnet.solana.com
          anchor build
