name: CI

on:
  push:
    branches:
      - utkarsh/github-workflow


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4ZPZVQTYONJGQ4AW
          aws-secret-access-key: S3onnT6o42kQnFv8Hk3gFCFy8TdPunhcOG6gZPCy
          aws-region: ap-south-1 # e.g., us-west-2

      # Step 3: Log in to Amazon ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 879381284080.dkr.ecr.ap-south-1.amazonaws.com

      # Step 4: Pull the Docker image from ECR
      - name: Pull Docker image
        run: |
          docker pull 879381284080.dkr.ecr.ap-south-1.amazonaws.com/rust-ctf:latest

      # Step 5: Copy Keypair from GitHub Secret
      - name: Create fee-pair.keyjson from GitHub secret
        run: |
          mkdir -p ./app
          echo "${{ secrets.FEE_PAIR_KEY }}" > ./app/fee-payer-keypair.json
          chmod 600 ./app/fee-pair-keypair.json

      # Step 6: Run the Docker container and configure Solana and Anchor
      - name: Run container and build
        run: |
          docker run --rm \
            -v $(pwd):/root/app \
            879381284080.dkr.ecr.ap-south-1.amazonaws.com/rust-ctf:latest \
            bash -c "
              # Configure Solana
              source /root/.bashrc && \
              solana config set --url https://api.devnet.solana.com && \
              solana config set --keypair /root/app/fee-payer-keypair.json && \
              anchor build
            "
